name: Go

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: go build

    - name: Build the Docker image and push it
      run: |
       export CURR_DATE=$(date +%s)
       echo $CURR_DATE
       docker build . --file Dockerfile --tag ghcr.io/ilja2209/batch-manager-ui:$CURR_DATE
       docker push ghcr.io/ilja2209/batch-manager-ui:$CURR_DATE
